Include yarn upgrade in update-verovio

diff --git a/update-verovio b/update-verovio
--- a/update-verovio
+++ b/update-verovio
@@ -5,7 +5,7 @@
 # Requires emscripten and git
 
 BUILDDIR="verovio-build"
-USAGE="./update-verovio [-b build-directory [-d]] [-l local-verovio] [-h]\n\n-b | --build-dir\t\tSpecify the build directory for verovio.\n-d | --delete\t\tDelete the build directory after building.\n-l | --local\t\tSpecify the path to a preexisting root of verovio source.\n-h | --help\t\tDisplay this dialogue.\n"
+USAGE="./update-verovio [-b build-directory [-d]] [-l local-verovio] [-h]\n\n-b | --build-dir\t\tSpecify the build directory for verovio.\n-d | --delete\t\tDelete the build directory after building.\n-l | --local\t\tSpecify the path to a preexisting root of verovio source.\n-s | --standalone\t\tBuild a standalone verovio toolkit (not an npm package).\n-h | --help\t\tDisplay this dialogue.\n"
 
 GIT=`which git`
 if [[ 0 -ne $? ]]; then
@@ -15,6 +15,11 @@ fi
 which emcc > /dev/null 2>&1
 if [[ 0 -ne $? ]]; then
     echo >&2 "Emscripten (emcc) could not be found.";
+    exit 127;
+fi
+which yarn > /dev/null 2>&1
+if [[ 0 -ne $? ]]; then
+    echo >&2 "Yarn could not be found.";
     exit 127;
 fi
 
@@ -90,7 +95,8 @@ fi
 if [ "$STANDALONE" ]; then
    cp "$BUILDDIR/emscripten/build/verovio-toolkit.js" src/
 else
-   cp -R "$BUILDDIR/emscripten/npm-dev" src/verovio-dev
+   cp -R "$BUILDDIR/emscripten/npm-dev/" src/verovio-dev
+   yarn upgrade verovio-dev
 fi
 
 if [ "$DELETE" ]; then
